version: '3'
services:
        ansible:
                container_name: ansible
                image: pkc/ansible
                command: sleep infinity
                volumes:
                  - ./playbook:/playbook
                extra_hosts:
                  - "host.docker.internal:host-gateway"