version: '3'
services:
        ansible:
                container_name: ansible
                image: bkoo/ansible
                command: sleep infinity
                volumes:
                  - ./ansible:/ansible
                extra_hosts:
                  - "host.docker.internal:host-gateway"